language: r
cache: packages

before_install:
- R -e 'install.packages("remotes")'
- R -e 'remotes::install_github("r-lib/covr")'

install:
- R -e 'install.packages(c("devtools", "testthat"))'
 script:
   - R CMD build .
   - R CMD check *tar.gz
   - R -e 'covr::codecov()'
